### ISSUE TITLE
naively running 'make' fails

### ISSUE THREAD

**Issue by bbolker** [dushoff/sherif#3]
From a fresh clone of the repo, running on a 32-bit Ubuntu 12.04 virtual machine, I get:

```
cp: cannot stat `../../lib/sherif': No such file or directory
```

Various harmless warnings about Rd files (documentation etc.)

And at the end:

```
Loading required package: snow
Created directory: /home/bolker/.sfCluster/restore
snowfall 1.84-6 initialized: sequential execution, one CPU.

sfExportAll() ignored in sequential mode.

Error: expecting a string
Execution halted
```

**Comment by davidchampredon** [comment]
On Oct 5, 2015, at 11:50 AM, Ben Bolker notifications@github.com wrote:
Ben - that should be working now. Thanks for testing.

DC

**Comment by bbolker** [comment]
looks fixed, thanks.
